Repository fga-eps-mds/MDS-2020-2-G9, pull requests merged in 2021-05, with the labels that each got.

#158 Att_Roadmap
  docs/roadmap.md
Labels: documentation, organização

#152 #148 Atualizando a pagina historico
  med_app/lib/constants.dart
  med_app/lib/screens/historico/components/body.dart
Labels: Protótipo, enhancement

#161 #160 Preview Sprint 12
  docs/Sprints/Gráficos/Burn Down (6).jpeg
  docs/Sprints/Gráficos/Velocity tracking (4).jpeg
  docs/Sprints/Planejamento/Sprint_12.md
  docs/Sprints/Revisão/Sprint_11_review.md
Labels: documentation, enhancement

#159 #156 Sincronizando as notificações com os horários
  med_app/lib/main.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/components/notification.dart
  med_app/lib/screens/medicacoes/medicacoes.dart
  med_app/pubspec.lock
  med_app/pubspec.yaml
Labels: enhancement, estudo

#167 #166 Notificações diárias
  med_app/android/app/src/main/AndroidManifest.xml
  med_app/lib/dataInit.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/components/horario.dart
  med_app/lib/screens/medicacoes/components/notification.dart
Labels: bug, enhancement

#169 #168 Splash Screen
  med_app/android/app/src/main/res/drawable/launch_background.xml
  med_app/android/app/src/main/res/drawable/teste_launch.png
  med_app/android/app/src/main/res/values/colors.xml
Labels: Protótipo, enhancement, estudo

#176 Calendário
  med_app/lib/constants.dart
  med_app/lib/screens/historico/components/body.dart
Labels: enhancement, estudo

#178 #148 consertando eventos no calendario
  med_app/lib/dataInit.dart
  med_app/lib/screens/historico/components/body.dart
  med_app/lib/screens/historico/historico.dart
Labels: enhancement

#165 #148 Consertando erro nas branchs
  med_app/lib/constants.dart
  med_app/lib/dataInit.dart
  med_app/lib/screens/historico/components/body.dart
  med_app/lib/screens/historico/historico.dart
Labels: Protótipo, enhancement

#179 #175 assets
  med_app/android/app/src/main/res/drawable/ic_launcher.png
  med_app/android/app/src/main/res/drawable/launch_background.xml
  med_app/android/app/src/main/res/drawable/medassistant.png
  med_app/android/app/src/main/res/drawable/teste_launch.png
  med_app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  med_app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  med_app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  med_app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  med_app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  med_app/android/app/src/main/res/values/colors.xml
  med_app/lib/dataInit.dart
  med_app/lib/screens/historico/historico.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/notification.dart
Labels: discussão, enhancement

#182 #181 Att_Roadmap
  docs/roadmap.md
Labels: documentation, organização

#170 #162 layout da pagina configuracoes
  med_app/lib/screens/configs/components/body.dart
  med_app/lib/screens/configs/components/musicas.dart
  med_app/lib/screens/configs/components/option_models.dart
  med_app/lib/screens/configs/configs.dart
Labels: Protótipo, enhancement, organização

#183 Code/#180 finais
  med_app/lib/screens/configs/components/body.dart
  med_app/lib/screens/configs/components/musicas.dart
  med_app/lib/screens/configs/components/option_models.dart
  med_app/lib/screens/configs/configs.dart
  med_app/lib/screens/historico/components/body.dart
  med_app/lib/screens/historico/historico.dart
Labels: discussão, enhancement
