Repository fga-eps-mds/MDS-2020-2-G9, pull requests merged in 2021-04, with the labels that each got.

#115 Docs/#114 documento de metodologia
  README.md
  docs/documentacao_metodologia.md
Labels: documentation, enhancement

#120 #119 Relatórios de Sprints
  docs/Sprints/Gráficos/Burn Down (3).jpeg.jpeg
  docs/Sprints/Gráficos/Velocity tracking (1).jpeg
  docs/Sprints/Planejamento/Sprint_8.md
  docs/Sprints/Revisão/Sprint_7_review.md
  docs/Sprints/Templates/planejamento_template.md
  docs/Sprints/Templates/revisao_template.md
Labels: documentation, enhancement

#122 #121 adicionando a sprint 7 no roadmap
  docs/roadmap.md
Labels: documentation, enhancement

#125 Docs/#108 documento de riscos
  docs/documento_de_risco.md
Labels: documentation, enhancement

#123 Dev/#118 medicacoes
  med_app/lib/constants.dart
  med_app/lib/screens/medicacoes/components/alarm_info.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/components/horario.dart
  med_app/lib/screens/medicacoes/medicacoes.dart
Labels: enhancement

#126 docs/#116 criando categorias
  docs/documento_de_visao.md
Labels: documentation, estudo

#133 #132 Relatórios de Sprints
  docs/Sprints/Gráficos/Burn Down (4).jpeg
  docs/Sprints/Gráficos/Velocity tracking (2).jpeg
  docs/Sprints/Planejamento/Sprint_8.md
  docs/Sprints/Planejamento/Sprint_9.md
  docs/Sprints/Revisão/Sprint_8_review.md
Labels: discussão, documentation

#134 #118 página de cadastros
  med_app/lib/main.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/components/horario.dart
Labels: enhancement

#131 Dev/#130 Local Notification
  med_app/android/app/src/main/AndroidManifest.xml
  med_app/android/app/src/main/res/drawable/ic_launcher.png
  med_app/android/app/src/main/res/raw/android_music.wav
  med_app/android/app/src/main/res/raw/drama_total.mp3
  med_app/android/settings_aar.gradle
  med_app/lib/main.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/medicacoes.dart
  med_app/pubspec.lock
  med_app/pubspec.yaml
Labels: duplicate, enhancement, estudo, organização

#129 #127 Implementação do calendário
  med_app/lib/constants.dart
  med_app/lib/screens/historico/components/body.dart
  med_app/pubspec.lock
  med_app/pubspec.yaml
Labels: Protótipo, discussão, enhancement

#142 #138 Atualizando o documento de riscos
  docs/Sprints/Gráficos/burndownchartRISCO.jpg
  docs/Sprints/Gráficos/burndownchartRISCO.png
  docs/documento_de_risco.md
Labels: documentation, enhancement

#137 Criação de um banco de dados
  med_app/lib/constants.dart
  med_app/lib/dataInit.dart
  med_app/lib/main.dart
  med_app/lib/navBar.dart
  med_app/lib/screens/historico/components/body.dart
  med_app/lib/screens/medicacoes/components/alarm_info.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/medicacoes.dart
  med_app/pubspec.lock
  med_app/pubspec.yaml
Labels: enhancement, estudo, organização

#143 #141 atulizar o roadmap
  docs/roadmap.md
Labels: documentation

#145 #144 Relatórios das Sprints
  docs/Sprints/Gráficos/Burn Down (5).jpeg
  docs/Sprints/Gráficos/Velocity tracking (3).jpeg
  docs/Sprints/Planejamento/Sprint_11.md
  docs/Sprints/Revisão/Sprint_9_review.md
Labels: discussão, documentation

#147 #146 Testes do GitHub Actions
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/medicacoes.dart
  med_app/test/widget_test.dart
Labels: GH pages, bug

#151 função de Deletar dados SQlite
  med_app/lib/dataInit.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
Labels: enhancement, estudo

#153 adicionando diagrama
  docs/assets/MDS-G9.png
  docs/documento_de_arquitetura.md
Labels: documentation, enhancement, organização

#155 Dados da página de cadastro
  med_app/lib/screens/medicacoes/components/alarm_info.dart
  med_app/lib/screens/medicacoes/components/cadastro.dart
  med_app/lib/screens/medicacoes/components/horario.dart
Labels: enhancement, estudo
