Repository fga-eps-mds/MDS-2020-2-G9, pull requests merged in 2021-03, with the labels that each got.

#6 organizacao do repositorio
  .github/ISSUE_TEMPLATE/geral.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  docs/Canvas.pdf
  docs/Projeto_MDS.docx
Labels: documentation

#11 adicionado templates de planejamento/revisao
  docs/Sprints/Planejamento/Sprint_3.md
  docs/Sprints/Templates/planejamento_template.md
  docs/Sprints/Templates/revisao_template.md
Labels: documentation

#15 #12 Adiciona políticas.
  docs/Politicas/branches.md
  docs/Politicas/commits.md
  docs/Politicas/issues.md
  docs/Politicas/pullrequests.md
Labels: documentation

#17 #12 corrige erros gramaticais
  docs/Politicas/branches.md
Labels: fix

#19 #18 adiciona termo de abertura
  docs/termo_de_abertura.md
Labels: documentation

#27 Sprint_3
  docs/Sprints/Planejamento/Sprint_0.md
  docs/Sprints/Planejamento/Sprint_1.md
  docs/Sprints/Planejamento/Sprint_2.md
  docs/Sprints/Planejamento/Sprint_3.md
  docs/Sprints/Planejamento/Sprint_4.md
Labels: documentation

#30 Review da Sprint 3
  docs/Sprints/Revisão/Sprint_3_review.md
Labels: documentation

#34 #33 atualiza roadmap
  docs/roadmap.md
  flutter_application_1/lib/clock_digital.dart
Labels: documentation

#40 #39 altera logo
  README.md
  docs/assets/MED-logo.png
  docs/assets/logoEMPRESAfarmatech.png
  docs/assets/logoEMPRESAfarmatechBRANCO.png
Labels: documentation

#45 #44 cria contributing.md
  CONTRIBUTING.md
Labels: documentation

#49 #48 Criação do primeiro arquivo backlog
  docs/backlog.md
Labels: discussão, documentation

#41 #16 Criação do documento de arquitetura
  docs/documento_de_arquitetura.md
Labels: documentation

#53 #47 adiciona prototipo home
  imagens/logoEMPRESAfarmatech.png
  imagens/logoEMPRESAfarmatechBRANCO.png
  imagens/medassistantBRANCO.png
  prototipo/home.png
Labels: documentation

#54 Docs/#51 review sprint04
  docs/Sprints/Revisão/Sprint_4_review.md
Labels: documentation

#62 #60 Atualiza os dados do README
  README.md
Labels: documentation, enhancement

#68 # 65 Incrementação da Introdução e adição das referências
  docs/documento_de_visao.md
Labels: documentation, enhancement

#72 #71 Adiciona o protótipo de baixa fidelidade da página "Home"
  prototipo/Calendar_baixa_fidelidade.png
  prototipo/Home_baixa_fidelidade.jpeg
  prototipo/Medication(page 2)_baixa_fidelidade.jpeg
  prototipo/Medication(page 3)_baixa_fidelidade.jpeg
  prototipo/Medication(page 4)_baixa_fidelidade.jpeg
  prototipo/Medication_baixa_fidelidade.jpeg
Labels: documentation, enhancement

#76 #75 Atualização do documento de comunicação com as novas ferramentas
  docs/documento_comunicacao.md
Labels: documentation, enhancement

#77 #70 att o roadmap
  docs/roadmap.md
Labels: documentation

#74 #67 Adiciona o protótipo de alta fidelidade
  prototipo/home.png
  prototipo/medicacoes.png
Labels: documentation, duplicate, enhancement

#80 #78 Aumentar o escopo do documento de Backlog
  docs/backlog.md
Labels: documentation, enhancement

#83 Atualiza pagina Historico
  prototipo/alta fidelidade/historico.png
  prototipo/alta fidelidade/home.png
  prototipo/alta fidelidade/medicacoes.png
  prototipo/baixa fidelidade/historico.png
  prototipo/baixa fidelidade/home.jpeg
  prototipo/baixa fidelidade/medicacoes-2.jpeg
  prototipo/baixa fidelidade/medicacoes-3.jpeg
  prototipo/baixa fidelidade/medicacoes-4.jpeg
  prototipo/baixa fidelidade/medicacoes.jpeg
  prototipo/histórico.jpeg
  prototipo/home.png
  prototipo/medicacoes.png
Labels: documentation, enhancement

#85 #58 Criação do Fluxo de Usuário
  prototipo/Fluxo de Usuário.jpeg
Labels: Protótipo, documentation

#87 Docs/#84 arquivo protótipos
  README.md
  docs/documento_prototipos.md
Labels: Protótipo, documentation

#90 #79 review da sprint 5
  docs/Sprints/Revisão/Sprint_5_review.md
Labels: documentation

#89 #88 Conluindo o planejamento da sprint 5.
  docs/Sprints/Planejamento/Sprint_5.md
  docs/Sprints/Planejamento/Sprint_6.md
Labels: documentation

#92 #91 Bugfix ponteiro das horas "clock_view.dart"
  flutter_application_1/lib/clock_view.dart
Labels: bug, enhancement

#94 #93 adiciona icones
  flutter_application_1/assets/tabler-icon-chevron-left.svg
  flutter_application_1/assets/tabler-icon-chevron-right.svg
  flutter_application_1/assets/tabler-icon-clock.svg
  flutter_application_1/assets/tabler-icon-home.svg
  flutter_application_1/assets/tabler-icon-menu-2.svg
  flutter_application_1/assets/tabler-icon-pill.svg
  flutter_application_1/assets/tabler-icon-plus.svg
Labels: enhancement

#96 #95 adiciona showcase
  README.md
  docs/assets/Showcase.png
  flutter_application_1/assets/paleta.png
Labels: documentation, enhancement

#104 #93 Criação do menu inferior, já funcional para mudanças de páginas
  med_app/lib/main.dart
  med_app/lib/screens/home/components/body.dart
  med_app/lib/screens/home/components/menu_bar.dart
  med_app/lib/screens/home/home.dart
Labels: discussão, enhancement, organização

#97 Docs/#86
  docs/documento_de_arquitetura.md
Labels: documentation

#106 Docs/#100 att roadmap sprint 5
  docs/roadmap.md
Labels: documentation

#107 #105 Review Sprints
  docs/Sprints/Gráficos/Burn Down (1).jpeg
  docs/Sprints/Gráficos/Burn Down (2).jpeg
  docs/Sprints/Planejamento/Sprint_7.md
  docs/Sprints/Revisão/Sprint_5_review.md
  docs/Sprints/Revisão/Sprint_6_review.md
  docs/Sprints/Templates/revisao_template.md
  med_app/lib/main.dart
  med_app/lib/screens/home/home.dart
Labels: discussão, documentation, organização

#111 Code/#110 medication page
  med_app/assets/fonts/OpenSans-Bold.ttf
  med_app/assets/fonts/OpenSans-Regular.ttf
  med_app/assets/fonts/OpenSans-SemiBold.ttf
  med_app/lib/constants.dart
  med_app/lib/screens/medicacoes/components/alarm_info.dart
  med_app/lib/screens/medicacoes/components/body.dart
  med_app/pubspec.yaml
Labels: Protótipo, enhancement, estudo
